sudo: required
services:
  - docker

before_install:
  - docker build -t sandeepsanvi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sandeepsanvi/react-test npm test

after_success:
  - docker build -t sandeepsanvimulti-client ./client
  - docker build -t sandeepsanvimulti-nginx ./nginx
  - docker build -t sandeepsanvimulti-server ./server
  - docker build -t sandeepsanvimulti-worker ./worker
  # Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push the image to Docker hub
  - docker push sandeepsanvimulti-client
  - docker push sandeepsanvimulti-nginx
  - docker push sandeepsanvimulti-server
  - docker push sandeepsanvimulti-worker