sudo: required
services:
  - docker 

before_install:
  -docker build -t sandeep/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sandeep/react-test npm test

after_success:
  - docker build -t sandeeep/multi-client ./client
  - docker build -t sandeeep/multi-nginx ./nginx
  - docker build -t sandeeep/multi-server ./server
  - docker build -t sandeeep/multi-worker ./worker

#Login to docker cli
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Push the imaged to Docket hub
- docker push sandeeep/multi-client
- docker push sandeeep/multi-nginx
- docker push sandeeep/multi-server
- docker push sandeeep/multi-worker