sudo: required
services:
  - docker

before_install:
  - docker build -t sandeepsanvi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sandeepsanvi/react-test npm test

after_success:
  - docker build -t sandeepsanvi/multi-client ./client
  - docker build -t sandeepsanvi/multi-nginx ./nginx
  - docker build -t sandeepsanvi/multi-server ./server
  - docker build -t sandeepsanvi/multi-worker ./worker
  # Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push the image to Docker hub
  - docker push sandeepsanvi/multi-client
  - docker push sandeepsanvi/multi-nginx
  - docker push sandeepsanvi/multi-server
  - docker push sandeepsanvi/multi-worker